# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 05_slope.py
# Created on: 2020-08-18 13:47:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")


# Local variables:
mosaic_tif = "mosaic.tif"
slope_tif = "E:\\asesorias\\angie\\raster\\dem\\slope\\slope.tif"
print slope_tif

# Process: Slope
arcpy.gp.Slope_sa(mosaic_tif, slope_tif, "DEGREE", "1")
print "Done!"
