# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# mosaicking.py
# Created on: 2020-08-18 12:55:19.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
eu_dem_v11_E70N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E70N20.TIF"
eu_dem_v11_E60N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E60N20.TIF"
eu_dem_v11_E60N10_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E60N10.TIF"
eu_dem_v11_E50N50_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N50.TIF"
eu_dem_v11_E50N40_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N40.TIF"
eu_dem_v11_E50N30_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N30.TIF"
eu_dem_v11_E30N40_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N40.TIF"
eu_dem_v11_E30N50_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N50.TIF"
eu_dem_v11_E40N10_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N10.TIF"
eu_dem_v11_E40N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N20.TIF"
eu_dem_v11_E40N30_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N30.TIF"
eu_dem_v11_E40N40_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N40.TIF"
eu_dem_v11_E30N30_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N30.TIF"
eu_dem_v11_E50N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N20.TIF"
eu_dem_v11_E30N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N20.TIF"
eu_dem_v11_E50N10_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N10.TIF"
eu_dem_v11_E30N10_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N10.TIF"
eu_dem_v11_E40N50_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N50.TIF"
eu_dem_v11_E00N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E00N20.TIF"
eu_dem_v11_E10N00_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E10N00.TIF"
eu_dem_v11_E10N10_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E10N10.TIF"
eu_dem_v11_E10N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E10N20.TIF"
eu_dem_v11_E20N10_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N10.TIF"
eu_dem_v11_E20N20_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N20.TIF"
eu_dem_v11_E20N30_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N30.TIF"
eu_dem_v11_E20N40_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N40.TIF"
eu_dem_v11_E20N50_TIF = "E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N50.TIF"
mosaic = "E:\\asesorias\\angie\\raster\\dem\\mosaic"

# Process: Mosaic To New Raster
arcpy.MosaicToNewRaster_management("E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E70N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E60N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E60N10.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N50.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N40.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N30.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N40.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N50.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N10.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N30.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N40.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N30.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E50N10.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E30N10.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E40N50.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E00N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E10N00.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E10N10.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E10N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N10.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N20.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N30.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N40.TIF;E:\\asesorias\\angie\\raster\\dem\\fill\\eu_dem_v11_E20N50.TIF", mosaic, "mosaic.tif", "", "32_BIT_FLOAT", "100", "1", "LAST", "FIRST")

